"""tag image

Revision ID: 79d88e2e21b6
Revises: 786864a67756
Create Date: 2026-09-22 13:54:01.877328+00:00
"""

from __future__ import annotations

import sqlalchemy as sa

from alembic import op

revision = "79d88e2e21b6"
down_revision = "786864a67756"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_posts_tenant_date"), table_name="posts")
    op.create_index(
        "ix_posts_tenant_date", "posts", ["tenant_id", "date"], unique=False, postgresql_ops={"date": "DESC"}
    )
    op.drop_index(op.f("ix_posts_tenant_engagement"), table_name="posts")
    op.create_index(
        "ix_posts_tenant_engagement",
        "posts",
        ["tenant_id", "engagement_score"],
        unique=False,
        postgresql_ops={"engagement_score": "DESC"},
    )
    op.drop_index(op.f("ix_posts_tenant_views"), table_name="posts")
    op.create_index(
        "ix_posts_tenant_views",
        "posts",
        ["tenant_id", "views"],
        unique=False,
        postgresql_ops={"views": "DESC"},
    )
    op.add_column("tags", sa.Column("image_key", sa.String(length=300), nullable=True))
    op.add_column("tags", sa.Column("image_source", sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tags", "image_source")
    op.drop_column("tags", "image_key")
    op.drop_index("ix_posts_tenant_views", table_name="posts", postgresql_ops={"views": "DESC"})
    op.create_index(
        op.f("ix_posts_tenant_views"), "posts", ["tenant_id", sa.literal_column("views DESC")], unique=False
    )
    op.drop_index(
        "ix_posts_tenant_engagement", table_name="posts", postgresql_ops={"engagement_score": "DESC"}
    )
    op.create_index(
        op.f("ix_posts_tenant_engagement"),
        "posts",
        ["tenant_id", sa.literal_column("engagement_score DESC")],
        unique=False,
    )
    op.drop_index("ix_posts_tenant_date", table_name="posts", postgresql_ops={"date": "DESC"})
    op.create_index(
        op.f("ix_posts_tenant_date"), "posts", ["tenant_id", sa.literal_column("date DESC")], unique=False
    )
    # ### end Alembic commands ###
