"""initial schema

Revision ID: 786864a67756
Revises:
Create Date: 2026-09-21 06:07:11.392308+00:00
"""

from __future__ import annotations

import pgvector.sqlalchemy  # noqa: F401  (HALFVEC type)
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision = "786864a67756"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.execute("CREATE EXTENSION IF NOT EXISTS unaccent")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "platform_admins",
        sa.Column("tg_user_id", sa.BigInteger(), nullable=False),
        sa.Column("note", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("tg_user_id"),
    )
    op.create_table(
        "telegram_accounts",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("phone", sa.String(length=32), nullable=False),
        sa.Column("tg_user_id", sa.BigInteger(), nullable=True),
        sa.Column("display_name", sa.String(length=128), nullable=True),
        sa.Column("session_enc", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("health", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("flood_wait_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("phone"),
    )
    op.create_table(
        "tenants",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("domain", sa.String(length=253), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("primary_lang", sa.String(length=8), nullable=False),
        sa.Column("locales", postgresql.ARRAY(sa.String(length=8)), nullable=False),
        sa.Column("bot_token_enc", sa.Text(), nullable=True),
        sa.Column("bot_id", sa.BigInteger(), nullable=True),
        sa.Column("bot_username", sa.String(length=64), nullable=True),
        sa.Column("webhook_secret", sa.String(length=64), nullable=True),
        sa.Column("domain_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("active_taxonomy_version_id", sa.BigInteger(), nullable=True),
        sa.Column("daily_chat_budget_usd", sa.Numeric(precision=8, scale=2), nullable=False),
        sa.Column("daily_studio_budget_usd", sa.Numeric(precision=8, scale=2), nullable=False),
        sa.Column("settings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("domain"),
        sa.UniqueConstraint("slug"),
    )
    op.create_index(op.f("ix_tenants_status"), "tenants", ["status"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("tg_user_id", sa.BigInteger(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=True),
        sa.Column("first_name", sa.String(length=128), nullable=True),
        sa.Column("last_name", sa.String(length=128), nullable=True),
        sa.Column("photo_url", sa.Text(), nullable=True),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tg_user_id"),
    )
    op.create_table(
        "audit_log",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("tenant_id", sa.BigInteger(), nullable=True),
        sa.Column("actor_user_id", sa.BigInteger(), nullable=True),
        sa.Column("action", sa.String(length=48), nullable=False),
        sa.Column("target", sa.String(length=128), nullable=True),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default="now()", nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_audit_log_tenant_created", "audit_log", ["tenant_id", "created_at"], unique=False)
    op.create_table(
        "channels",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("tenant_id", sa.BigInteger(), nullable=False),
        sa.Column("telegram_account_id", sa.BigInteger(), nullable=True),
        sa.Column("tg_channel_id", sa.BigInteger(), nullable=False),
        sa.Column("access_hash", sa.BigInteger(), nullable=True),
        sa.Column("username", sa.String(length=64), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("about", sa.Text(), nullable=True),
        sa.Column("photo_key", sa.String(length=512), nullable=True),
        sa.Column("is_private", sa.Boolean(), nullable=False),
        sa.Column("noforwards", sa.Boolean(), nullable=False),
        sa.Column("participants_count", sa.Integer(), nullable=True),
        sa.Column("backfill_status", sa.String(length=16), nullable=False),
        sa.Column("backfill_checkpoint", sa.BigInteger(), nullable=False),
        sa.Column("backfill_total_estimate", sa.Integer(), nullable=True),
        sa.Column("last_live_update_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_resync_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["telegram_account_id"], ["telegram_accounts.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id"),
        sa.UniqueConstraint("tg_channel_id"),
    )
    op.create_index("ix_channels_tenant", "channels", ["tenant_id"], unique=False)
    op.create_table(
        "chat_sessions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column("visitor_id", sa.String(length=64), nullable=True),
        sa.Column("ip_hash", sa.String(length=64), nullable=True),
        sa.Column("kind", sa.String(length=12), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=True),
        sa.Column("locale", sa.String(length=8), nullable=True),
        sa.Column("seed_post_id", sa.BigInteger(), nullable=True),
        sa.Column("message_count", sa.Integer(), nullable=False),
        sa.Column("total_cost_usd", sa.Numeric(precision=10, scale=6), nullable=False),
        sa.Column("summary_note", sa.Text(), nullable=True),
        sa.Column("last_message_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tenant_id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_chat_sessions_tenant_id"), "chat_sessions", ["tenant_id"], unique=False)
    op.create_index(
        "ix_chat_sessions_tenant_user_last",
        "chat_sessions",
        ["tenant_id", "user_id", "last_message_at"],
        unique=False,
    )
    op.create_table(
        "dimensions",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("key", sa.String(length=48), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("labels", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("extraction_hint", sa.Text(), nullable=True),
        sa.Column("is_universal", sa.Boolean(), nullable=False),
        sa.Column("is_visible", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "key", name="uq_dimensions_tenant_key"),
    )
    op.create_index(op.f("ix_dimensions_tenant_id"), "dimensions", ["tenant_id"], unique=False)
    op.create_table(
        "ideas",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("tag_ids", postgresql.ARRAY(sa.BigInteger()), nullable=False),
        sa.Column("related_post_ids", postgresql.ARRAY(sa.BigInteger()), nullable=False),
        sa.Column("source_chat_message_id", sa.BigInteger(), nullable=True),
        sa.Column("tenant_id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ideas_tenant_id"), "ideas", ["tenant_id"], unique=False)
    op.create_index("ix_ideas_tenant_status_pos", "ideas", ["tenant_id", "status", "position"], unique=False)
    op.create_table(
        "job_runs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("tenant_id", sa.BigInteger(), nullable=True),
        sa.Column("type", sa.String(length=24), nullable=False),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("procrastinate_job_id", sa.BigInteger(), nullable=True),
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("progress", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("cost_usd", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_job_runs_status", "job_runs", ["status"], unique=False)
    op.create_index(
        "ix_job_runs_tenant_type_created", "job_runs", ["tenant_id", "type", "created_at"], unique=False
    )
    op.create_table(
        "llm_batches",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("anthropic_batch_id", sa.String(length=64), nullable=False),
        sa.Column("purpose", sa.String(length=16), nullable=False),
        sa.Column("model", sa.String(length=48), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("request_count", sa.Integer(), nullable=False),
        sa.Column("succeeded", sa.Integer(), nullable=False),
        sa.Column("errored", sa.Integer(), nullable=False),
        sa.Column("expired", sa.Integer(), nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ingested_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cost_usd", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column("tenant_id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("anthropic_batch_id"),
    )
    op.create_index(op.f("ix_llm_batches_tenant_id"), "llm_batches", ["tenant_id"], unique=False)
    op.create_table(
        "taxonomy_versions",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("version_no", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("model", sa.String(length=48), nullable=False),
        sa.Column("candidate_stats", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("proposal", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("diff", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("cost_usd", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column("built_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("applied_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("tenant_id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "version_no", name="uq_taxonomy_versions_tenant_no"),
    )
    op.create_index(op.f("ix_taxonomy_versions_tenant_id"), "taxonomy_versions", ["tenant_id"], unique=False)
    op.create_table(
        "tenant_members",
        sa.Column("tenant_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("role", sa.String(length=12), nullable=False),
        sa.Column("verified_admin_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("dm_chat_id", sa.BigInteger(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("tenant_id", "user_id"),
    )
    op.create_table(
        "threads",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("slug", sa.String(length=96), nullable=False),
        sa.Column("title", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("summary", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("first_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("post_count", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("citations", postgresql.ARRAY(sa.BigInteger()), nullable=False),
        sa.Column("tenant_id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_threads_tenant_id"), "threads", ["tenant_id"], unique=False)
    op.create_table(
        "uploads",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column("object_key", sa.String(length=512), nullable=False),
        sa.Column("thumb_key", sa.String(length=512), nullable=True),
        sa.Column("mime", sa.String(length=128), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("tenant_id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_uploads_tenant_id"), "uploads", ["tenant_id"], unique=False)
    op.create_table(
        "usage_ledger",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("tenant_id", sa.BigInteger(), nullable=True),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("provider", sa.String(length=16), nullable=False),
        sa.Column("model", sa.String(length=48), nullable=False),
        sa.Column("purpose", sa.String(length=24), nullable=False),
        sa.Column("input_tokens", sa.BigInteger(), nullable=False),
        sa.Column("output_tokens", sa.BigInteger(), nullable=False),
        sa.Column("cache_write_tokens", sa.BigInteger(), nullable=False),
        sa.Column("cache_read_tokens", sa.BigInteger(), nullable=False),
        sa.Column("requests", sa.Integer(), nullable=False),
        sa.Column("cost_usd", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "day", "model", "purpose", name="uq_usage_ledger_key"),
    )
    op.create_index(op.f("ix_usage_ledger_tenant_id"), "usage_ledger", ["tenant_id"], unique=False)
    op.create_table(
        "chat_messages",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(length=12), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("content_blocks", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("citations", postgresql.ARRAY(sa.BigInteger()), nullable=False),
        sa.Column("model", sa.String(length=48), nullable=True),
        sa.Column("usage", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("cost_usd", sa.Numeric(precision=10, scale=6), nullable=False),
        sa.Column("stop_reason", sa.String(length=24), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("tenant_id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["session_id"], ["chat_sessions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_chat_messages_session", "chat_messages", ["session_id", "id"], unique=False)
    op.create_index(op.f("ix_chat_messages_tenant_id"), "chat_messages", ["tenant_id"], unique=False)
    op.create_table(
        "drafts",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column("idea_id", sa.BigInteger(), nullable=True),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("html", sa.Text(), nullable=False),
        sa.Column("media", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("disable_preview", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("publish_job_id", sa.BigInteger(), nullable=True),
        sa.Column("published_tg_message_id", sa.BigInteger(), nullable=True),
        sa.Column("published_post_id", sa.BigInteger(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("publish_error", sa.Text(), nullable=True),
        sa.Column("suggested_tags", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("ai_generated", sa.Boolean(), nullable=False),
        sa.Column("ai_prompt", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("tenant_id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["idea_id"], ["ideas.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_drafts_tenant_id"), "drafts", ["tenant_id"], unique=False)
    op.create_index(
        "ix_drafts_tenant_status_sched", "drafts", ["tenant_id", "status", "scheduled_at"], unique=False
    )
    op.create_table(
        "posts",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("channel_id", sa.BigInteger(), nullable=False),
        sa.Column("tg_message_id", sa.BigInteger(), nullable=False),
        sa.Column("grouped_id", sa.BigInteger(), nullable=True),
        sa.Column("is_album_root", sa.Boolean(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("text_norm", sa.Text(), nullable=False),
        sa.Column("entities", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("html", sa.Text(), nullable=False),
        sa.Column("date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("edit_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("views", sa.Integer(), nullable=False),
        sa.Column("forwards", sa.Integer(), nullable=False),
        sa.Column("reactions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("reactions_total", sa.Integer(), nullable=False),
        sa.Column("engagement_score", sa.Float(), nullable=False),
        sa.Column("reply_to_tg_message_id", sa.BigInteger(), nullable=True),
        sa.Column("forward_from", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("media_kind", sa.String(length=16), nullable=False),
        sa.Column("poll", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("language", sa.String(length=12), nullable=True),
        sa.Column("title", sa.String(length=160), nullable=True),
        sa.Column("summary", sa.String(length=400), nullable=True),
        sa.Column("index_status", sa.String(length=16), nullable=False),
        sa.Column("extraction_version", sa.Integer(), nullable=True),
        sa.Column(
            "tsv",
            postgresql.TSVECTOR(),
            sa.Computed(
                "to_tsvector('simple', coalesce(text, '') || ' ' || coalesce(text_norm, ''))", persisted=True
            ),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["channel_id"], ["channels.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("channel_id", "tg_message_id", name="uq_posts_channel_msg"),
    )
    op.create_index(
        "ix_posts_tenant_date", "posts", ["tenant_id", "date"], unique=False, postgresql_ops={"date": "DESC"}
    )
    op.create_index(
        "ix_posts_tenant_engagement",
        "posts",
        ["tenant_id", "engagement_score"],
        unique=False,
        postgresql_ops={"engagement_score": "DESC"},
    )
    op.create_index("ix_posts_tenant_grouped", "posts", ["tenant_id", "grouped_id"], unique=False)
    op.create_index(op.f("ix_posts_tenant_id"), "posts", ["tenant_id"], unique=False)
    op.create_index("ix_posts_tenant_index_status", "posts", ["tenant_id", "index_status"], unique=False)
    op.create_index(
        "ix_posts_tenant_views",
        "posts",
        ["tenant_id", "views"],
        unique=False,
        postgresql_ops={"views": "DESC"},
    )
    op.create_index(
        "ix_posts_text_norm_trgm",
        "posts",
        ["text_norm"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"text_norm": "gin_trgm_ops"},
    )
    op.create_index("ix_posts_tsv", "posts", ["tsv"], unique=False, postgresql_using="gin")
    op.create_table(
        "tags",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("dimension_id", sa.BigInteger(), nullable=False),
        sa.Column("slug", sa.String(length=96), nullable=False),
        sa.Column("canonical_name", sa.String(length=200), nullable=False),
        sa.Column("canonical_norm", sa.String(length=200), nullable=False),
        sa.Column("labels", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("parent_id", sa.BigInteger(), nullable=True),
        sa.Column("merged_into_id", sa.BigInteger(), nullable=True),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("is_pinned", sa.Boolean(), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("post_count", sa.Integer(), nullable=False),
        sa.Column("engagement_score", sa.Float(), nullable=False),
        sa.Column("first_seen_version", sa.Integer(), nullable=True),
        sa.Column("last_seen_version", sa.Integer(), nullable=True),
        sa.Column("embedding", pgvector.sqlalchemy.halfvec.HALFVEC(dim=1024), nullable=True),
        sa.Column("tenant_id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["dimension_id"], ["dimensions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["merged_into_id"], ["tags.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["parent_id"], ["tags.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "dimension_id", "canonical_norm", name="uq_tags_tenant_dim_norm"),
        sa.UniqueConstraint("tenant_id", "slug", name="uq_tags_tenant_slug"),
    )
    op.create_index(
        "ix_tags_tenant_dim_count", "tags", ["tenant_id", "dimension_id", "post_count"], unique=False
    )
    op.create_index(op.f("ix_tags_tenant_id"), "tags", ["tenant_id"], unique=False)
    op.create_table(
        "entity_summaries",
        sa.Column("tag_id", sa.BigInteger(), nullable=False),
        sa.Column("summary", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("citations", postgresql.ARRAY(sa.BigInteger()), nullable=False),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_stale", sa.Boolean(), nullable=False),
        sa.Column("cost_usd", sa.Numeric(precision=10, scale=6), nullable=False),
        sa.Column("tenant_id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["tag_id"], ["tags.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("tag_id"),
    )
    op.create_index(op.f("ix_entity_summaries_tenant_id"), "entity_summaries", ["tenant_id"], unique=False)
    op.create_table(
        "extractions",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("post_id", sa.BigInteger(), nullable=False),
        sa.Column("extractor_version", sa.Integer(), nullable=False),
        sa.Column("model", sa.String(length=48), nullable=False),
        sa.Column("prompt_version", sa.String(length=16), nullable=False),
        sa.Column("llm_batch_id", sa.BigInteger(), nullable=True),
        sa.Column("custom_id", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("usage", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("cost_usd", sa.Numeric(precision=10, scale=6), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("tenant_id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["llm_batch_id"], ["llm_batches.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["post_id"], ["posts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("post_id", "extractor_version", name="uq_extractions_post_version"),
    )
    op.create_index("ix_extractions_batch", "extractions", ["llm_batch_id"], unique=False)
    op.create_index(op.f("ix_extractions_tenant_id"), "extractions", ["tenant_id"], unique=False)
    op.create_index("ix_extractions_tenant_status", "extractions", ["tenant_id", "status"], unique=False)
    op.create_table(
        "media",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("post_id", sa.BigInteger(), nullable=False),
        sa.Column("position", sa.SmallInteger(), nullable=False),
        sa.Column("tg_file_unique_id", sa.String(length=64), nullable=False),
        sa.Column("tg_file_ref", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("mime", sa.String(length=128), nullable=True),
        sa.Column("size_bytes", sa.BigInteger(), nullable=True),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("duration_s", sa.Integer(), nullable=True),
        sa.Column("file_name", sa.String(length=255), nullable=True),
        sa.Column("object_key", sa.String(length=512), nullable=True),
        sa.Column("thumb_key", sa.String(length=512), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("external_url", sa.String(length=512), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["post_id"], ["posts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("post_id", "tg_file_unique_id", name="uq_media_post_file"),
    )
    op.create_index(op.f("ix_media_tenant_id"), "media", ["tenant_id"], unique=False)
    op.create_index("ix_media_tenant_post", "media", ["tenant_id", "post_id"], unique=False)
    op.create_index("ix_media_tenant_status", "media", ["tenant_id", "status"], unique=False)
    op.create_table(
        "post_chunks",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("post_id", sa.BigInteger(), nullable=False),
        sa.Column("position", sa.SmallInteger(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.halfvec.HALFVEC(dim=1024), nullable=True),
        sa.Column("embed_model", sa.String(length=32), nullable=True),
        sa.Column("embedded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tenant_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["post_id"], ["posts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("post_id", "position", name="uq_post_chunks_post_pos"),
    )
    op.create_index(
        "ix_post_chunks_embedding_hnsw",
        "post_chunks",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 128},
        postgresql_ops={"embedding": "halfvec_cosine_ops"},
    )
    op.create_index(op.f("ix_post_chunks_tenant_id"), "post_chunks", ["tenant_id"], unique=False)
    op.create_index("ix_post_chunks_tenant_post", "post_chunks", ["tenant_id", "post_id"], unique=False)
    op.create_table(
        "post_links",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("post_id", sa.BigInteger(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("url_norm", sa.Text(), nullable=False),
        sa.Column("domain", sa.String(length=253), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=True),
        sa.Column("title", sa.String(length=300), nullable=True),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("unfurled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("http_status", sa.Integer(), nullable=True),
        sa.Column("tenant_id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["post_id"], ["posts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_post_links_post", "post_links", ["post_id"], unique=False)
    op.create_index("ix_post_links_tenant_domain", "post_links", ["tenant_id", "domain"], unique=False)
    op.create_index(op.f("ix_post_links_tenant_id"), "post_links", ["tenant_id"], unique=False)
    op.create_table(
        "post_tags",
        sa.Column("post_id", sa.BigInteger(), nullable=False),
        sa.Column("tag_id", sa.BigInteger(), nullable=False),
        sa.Column("tenant_id", sa.BigInteger(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default="now()", nullable=False),
        sa.ForeignKeyConstraint(["post_id"], ["posts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tag_id"], ["tags.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("post_id", "tag_id"),
    )
    op.create_index(
        "ix_post_tags_tenant_tag_post", "post_tags", ["tenant_id", "tag_id", "post_id"], unique=False
    )
    op.create_table(
        "tag_aliases",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("tag_id", sa.BigInteger(), nullable=False),
        sa.Column("alias", sa.String(length=200), nullable=False),
        sa.Column("alias_norm", sa.String(length=200), nullable=False),
        sa.Column("lang", sa.String(length=8), nullable=True),
        sa.Column("source", sa.String(length=12), nullable=False),
        sa.Column("tenant_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["tag_id"], ["tags.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "tag_id", "alias_norm", name="uq_tag_aliases_tag_norm"),
    )
    op.create_index(op.f("ix_tag_aliases_tenant_id"), "tag_aliases", ["tenant_id"], unique=False)
    op.create_index("ix_tag_aliases_tenant_norm", "tag_aliases", ["tenant_id", "alias_norm"], unique=False)
    op.create_table(
        "tag_candidates",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("dimension_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("name_norm", sa.String(length=200), nullable=False),
        sa.Column("lang", sa.String(length=8), nullable=True),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.Column("sample_post_ids", postgresql.ARRAY(sa.BigInteger()), nullable=False),
        sa.Column("surface_forms", postgresql.ARRAY(sa.String(length=200)), nullable=False),
        sa.Column("mean_engagement", sa.Float(), nullable=False),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("mapped_tag_id", sa.BigInteger(), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tenant_id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["dimension_id"], ["dimensions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["mapped_tag_id"], ["tags.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id", "dimension_id", "name_norm", name="uq_tag_candidates_tenant_dim_norm"
        ),
    )
    op.create_index(op.f("ix_tag_candidates_tenant_id"), "tag_candidates", ["tenant_id"], unique=False)
    op.create_table(
        "thread_posts",
        sa.Column("thread_id", sa.BigInteger(), nullable=False),
        sa.Column("post_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["post_id"], ["posts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["thread_id"], ["threads.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("thread_id", "post_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("thread_posts")
    op.drop_index(op.f("ix_tag_candidates_tenant_id"), table_name="tag_candidates")
    op.drop_table("tag_candidates")
    op.drop_index("ix_tag_aliases_tenant_norm", table_name="tag_aliases")
    op.drop_index(op.f("ix_tag_aliases_tenant_id"), table_name="tag_aliases")
    op.drop_table("tag_aliases")
    op.drop_index("ix_post_tags_tenant_tag_post", table_name="post_tags")
    op.drop_table("post_tags")
    op.drop_index(op.f("ix_post_links_tenant_id"), table_name="post_links")
    op.drop_index("ix_post_links_tenant_domain", table_name="post_links")
    op.drop_index("ix_post_links_post", table_name="post_links")
    op.drop_table("post_links")
    op.drop_index("ix_post_chunks_tenant_post", table_name="post_chunks")
    op.drop_index(op.f("ix_post_chunks_tenant_id"), table_name="post_chunks")
    op.drop_index(
        "ix_post_chunks_embedding_hnsw",
        table_name="post_chunks",
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 128},
        postgresql_ops={"embedding": "halfvec_cosine_ops"},
    )
    op.drop_table("post_chunks")
    op.drop_index("ix_media_tenant_status", table_name="media")
    op.drop_index("ix_media_tenant_post", table_name="media")
    op.drop_index(op.f("ix_media_tenant_id"), table_name="media")
    op.drop_table("media")
    op.drop_index("ix_extractions_tenant_status", table_name="extractions")
    op.drop_index(op.f("ix_extractions_tenant_id"), table_name="extractions")
    op.drop_index("ix_extractions_batch", table_name="extractions")
    op.drop_table("extractions")
    op.drop_index(op.f("ix_entity_summaries_tenant_id"), table_name="entity_summaries")
    op.drop_table("entity_summaries")
    op.drop_index(op.f("ix_tags_tenant_id"), table_name="tags")
    op.drop_index("ix_tags_tenant_dim_count", table_name="tags")
    op.drop_table("tags")
    op.drop_index("ix_posts_tsv", table_name="posts", postgresql_using="gin")
    op.drop_index(
        "ix_posts_text_norm_trgm",
        table_name="posts",
        postgresql_using="gin",
        postgresql_ops={"text_norm": "gin_trgm_ops"},
    )
    op.drop_index("ix_posts_tenant_views", table_name="posts", postgresql_ops={"views": "DESC"})
    op.drop_index("ix_posts_tenant_index_status", table_name="posts")
    op.drop_index(op.f("ix_posts_tenant_id"), table_name="posts")
    op.drop_index("ix_posts_tenant_grouped", table_name="posts")
    op.drop_index(
        "ix_posts_tenant_engagement", table_name="posts", postgresql_ops={"engagement_score": "DESC"}
    )
    op.drop_index("ix_posts_tenant_date", table_name="posts", postgresql_ops={"date": "DESC"})
    op.drop_table("posts")
    op.drop_index("ix_drafts_tenant_status_sched", table_name="drafts")
    op.drop_index(op.f("ix_drafts_tenant_id"), table_name="drafts")
    op.drop_table("drafts")
    op.drop_index(op.f("ix_chat_messages_tenant_id"), table_name="chat_messages")
    op.drop_index("ix_chat_messages_session", table_name="chat_messages")
    op.drop_table("chat_messages")
    op.drop_index(op.f("ix_usage_ledger_tenant_id"), table_name="usage_ledger")
    op.drop_table("usage_ledger")
    op.drop_index(op.f("ix_uploads_tenant_id"), table_name="uploads")
    op.drop_table("uploads")
    op.drop_index(op.f("ix_threads_tenant_id"), table_name="threads")
    op.drop_table("threads")
    op.drop_table("tenant_members")
    op.drop_index(op.f("ix_taxonomy_versions_tenant_id"), table_name="taxonomy_versions")
    op.drop_table("taxonomy_versions")
    op.drop_index(op.f("ix_llm_batches_tenant_id"), table_name="llm_batches")
    op.drop_table("llm_batches")
    op.drop_index("ix_job_runs_tenant_type_created", table_name="job_runs")
    op.drop_index("ix_job_runs_status", table_name="job_runs")
    op.drop_table("job_runs")
    op.drop_index("ix_ideas_tenant_status_pos", table_name="ideas")
    op.drop_index(op.f("ix_ideas_tenant_id"), table_name="ideas")
    op.drop_table("ideas")
    op.drop_index(op.f("ix_dimensions_tenant_id"), table_name="dimensions")
    op.drop_table("dimensions")
    op.drop_index("ix_chat_sessions_tenant_user_last", table_name="chat_sessions")
    op.drop_index(op.f("ix_chat_sessions_tenant_id"), table_name="chat_sessions")
    op.drop_table("chat_sessions")
    op.drop_index("ix_channels_tenant", table_name="channels")
    op.drop_table("channels")
    op.drop_index("ix_audit_log_tenant_created", table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_table("users")
    op.drop_index(op.f("ix_tenants_status"), table_name="tenants")
    op.drop_table("tenants")
    op.drop_table("telegram_accounts")
    op.drop_table("platform_admins")
    # ### end Alembic commands ###
